# Site settings
title: 我的杂货铺
email: john.yitian@gmail.com
description: "这里的内容也许可以记录一些你感兴趣的东西."
baseurl: "/gitblog"
url: "https://github.com/lyt23/"

# Build settings
markdown: kramdown
permalink: pretty
